language: node_js

node_js:
  - "10"

script:
  - npm run lint
  - npm run build:chrome

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run semantic-release